"""Add followers

Revision ID: 05630bceae0d
Revises: 5ea98a85b28d
Create Date: 2025-12-27 22:03:37.252946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05630bceae0d'
down_revision = '5ea98a85b28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
