"""Add Report model and is_banned fields

Revision ID: 755215088e2f
Revises: ab54a387b895
Create Date: 2026-01-08 22:44:14.862431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755215088e2f'
down_revision = 'ab54a387b895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    op.drop_table('reports')
    # ### end Alembic commands ###
