"""Add allow_download to albums

Revision ID: 76dd43602451
Revises: 7a5b5a87744f
Create Date: 2026-01-07 11:35:08.063494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dd43602451'
down_revision = '7a5b5a87744f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_download', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('allow_download')

    # ### end Alembic commands ###
