"""Add cover_id to albums

Revision ID: 7a5b5a87744f
Revises: 3e34715c53c6
Create Date: 2026-01-07 11:22:53.127488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5b5a87744f'
down_revision = '3e34715c53c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_album_cover_photo', 'photos', ['cover_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint('fk_album_cover_photo', type_='foreignkey')
        batch_op.drop_column('cover_id')

    # ### end Alembic commands ###
