"""Add liked_photos_privacy to users

Revision ID: 827361c988d3
Revises: 57c751c27143
Create Date: 2026-01-07 10:56:32.856520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827361c988d3'
down_revision = '57c751c27143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_photos_privacy', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('liked_photos_privacy')

    # ### end Alembic commands ###
